const Map<String, String> enUs = {
  'language': 'Language',
  'appName': 'TimeFlow',
  'settings':'Settings',
  'theme_mode':'Theme mode',
  'user_info':'User Info',
  'about_app':'About App',
  'user_settings':'User Settings',
  'log_out':'Log Out',
  // SIGN IN
  'sign_up': 'Sign Up',
  'name': 'Name',
  'name_input': 'Enter your name',
  'email': 'Email',
  'email_input': 'Enter your email',
  'ac_pass': 'Password',
  'ac_pass_input': 'Enter your password',
  'signup_button': 'Register',
  'login_button': 'Login',
  'have_account?': 'Already have an account?',
  'invalid_email': 'Invalid email',
  'don\'t_have_account?': 'Don\'t have an account?',
  'login': 'Login',
  'error_signup': 'Error during sign up',
  'error_login': 'Incorrect email or password',

  // Report
  'reports': 'Reports',
  'report_empty': 'No reports yet',
  'report_nofount': 'Report not found',
  'report_drink': 'Drink Report',
  'report_food': 'Food Report',
  'report_bar': 'Bar Report',

  // Table
  'table_title': 'Tables',
  'table_page_empty': 'No tables available',
  'add_table': 'Add New Table',
  'table_name': 'Table Name',
  'input_table_name': 'Enter name',
  'table_number': 'Table Number',
  'input_table_number': 'Enter table number',
  'table_price': 'Price (per hour)',
  'input_table_price': 'Enter price',
  'busy_table': 'Book table named',
  'booking': 'Book',
  'table_delete': 'Delete table named?',
  'table_finish': 'Finish Table',
  'table_finish_want': 'Do you want to finish this table?',

  // Bar
  'bar_title': 'Bar',
  'food_empty': 'No food available',
  'food_delete': 'Delete food',
  'food_delete_want': 'Delete food named?',
  'food_add': 'Add New Food',
  'drink_empty': 'No drinks available',
  'edit_food': 'Edit Food',
  'edit_drink': 'Edit Drink',
  'delete_drink': 'Delete Drink',
  'drink_delete_want': 'Delete drink named?',
  'drink_add': 'Add Drink',
  'category': 'Category',
  'input_category': 'Enter category',

  // Payment
  'payment_title': 'Payment',
  'payment_page': 'Payment Page',
  'paymenting_sum': 'Payment Amount',
  'payment_sum': 'Paid Amount:',
  'payment_type': 'Payment Type',
  'cash': 'cash',
  'click': 'click',
  'description': 'Description',
  'payment_time': 'Payment Time:',
  'input_sum': 'Enter amount',
  'payment_report': 'Payment report Empty',

  // Session
  'start_time': 'Start Time:',
  'end_time': 'End Time:',
  'duration': 'Elapsed Time:',
  'table_sum': 'Table Price:',
  'bar_sum': 'Bar Price:',
  'total_sum': 'Total Price:',
  'completion': 'Complete',
  'session_null': 'No session found',
  'session_incomplete': 'Session data is incomplete',

  // Order
  'order_title': 'Orders',
  'order_time': 'Order Time:',
  'order_price': 'Order Price:',
  'order_add': 'Add Order',
  'order_food_empty': 'No food orders',
  'order_drink_empty': 'No drink orders',
  'food': 'Food',
  'drink': 'Drinks',

  // HOME
  'home': 'Home',
  'bar': 'Bar',

  // Public
  'save': 'Save',
  'price': 'Price',
  'status': 'Status',
  'amount': 'Amount',
  'amount_input': 'Enter quantity',
  'piece': 'pcs',
  'cencal': 'Cancel',
  'confirmation': 'Confirm',
  'delete': 'Delete',
  'yes': 'Yes',
  'error': 'Error',
  'loading': 'Loading',
  'add': 'Add',
  'title': 'Title',
  'input_title': 'Enter title',
  'size': 'Size',
  'update': 'Update',
};
