const Map<String, String> ruRu = {
  'appName': 'TimeFlow',
  'language':"язык",
  'settings':'Настройки',
  'theme_mode':'Темный режим',
  'user_info':'информация о пользователе',
  'user_settings':'Пользовательские настройки',
  'about_app':'O приложении',
  'log_out':'Выйти',
  'payment_report':'история выкупа пуста',



  'sign_up': 'Регистрация',
  'name': 'Имя',
  'name_input': 'Введите имя',
  'email': 'Эл. почта',
  'email_input': 'Введите эл. почту',
  'ac_pass': 'Пароль',
  'ac_pass_input': 'Введите пароль',
  'signup_button': 'Зарегистрироваться',
  'login_button': 'Войти',
  'have_account?': 'У вас уже есть аккаунт?',
  'invalid_email': 'Неверная эл. почта',
  'don\'t_have_account?': 'У вас нет аккаунта?',
  'login': 'Логин',
  'error_signup': 'Ошибка при регистрации',
  'error_login': 'Неверный логин или пароль',

  'reports': 'Отчеты',
  'report_empty': 'Отчетов пока нет',
  'report_nofount': 'Отчет не найден',
  'report_drink': 'Отчет по напиткам',
  'report_food': 'Отчет по еде',
  'report_bar': 'Барный отчет',

  'table_title': 'Столы',
  'table_page_empty': 'Столы отсутствуют',
  'add_table': 'Добавить стол',
  'table_name': 'Название стола',
  'input_table_name': 'Введите название',
  'table_number': 'Номер стола',
  'input_table_number': 'Введите номер',
  'table_price': 'Цена (в час)',
  'input_table_price': 'Введите цену',
  'busy_table': 'Занять стол с именем',
  'booking': 'Забронировать',
  'table_delete': 'Удалить стол с именем?',
  'table_finish': 'Завершить стол',
  'table_finish_want': 'Вы хотите завершить этот стол?',

  'bar_title': 'Бар',
  'food_empty': 'Еда отсутствует',
  'food_delete': 'Удалить еду',
  'food_delete_want': 'Удалить еду с именем?',
  'food_add': 'Добавить еду',
  'drink_empty': 'Напитки отсутствуют',
  'edit_food': 'Редактировать еду',
  'edit_drink': 'Редактировать напиток',
  'delete_drink': 'Удалить напиток',
  'drink_delete_want': 'Удалить напиток с именем?',
  'drink_add': 'Добавить напиток',
  'category': 'Категория',
  'input_category': 'Введите категорию',

  'payment_title': 'Оплата',
  'payment_page': 'Страница оплаты',
  'paymenting_sum': 'Сумма оплаты',
  'payment_sum': 'Оплачено:',
  'payment_type': 'Тип оплаты',
  'cash': 'наличные',
  'click': 'click',
  'description': 'Описание',
  'payment_time': 'Время оплаты:',
  'input_sum': 'Введите сумму',

  'start_time': 'Время начала:',
  'end_time': 'Время окончания:',
  'duration': 'Прошедшее время:',
  'table_sum': 'Цена стола:',
  'bar_sum': 'Цена бара:',
  'total_sum': 'Итого:',
  'completion': 'Завершить',
  'session_null': 'Сессия не найдена',
  'session_incomplete': 'Данные сессии неполные',

  'order_title': 'Заказы',
  'order_time': 'Время заказа:',
  'order_price': 'Сумма заказа:',
  'order_add': 'Добавить заказ',
  'order_food_empty': 'Нет заказов на еду',
  'order_drink_empty': 'Нет заказов на напитки',
  'food': 'Еда',
  'drink': 'Напитки',

  'home': 'Главная',
  'bar': 'Бар',

  'save': 'Сохранить',
  'price': 'Цена',
  'status': 'Статус',
  'amount': 'Количество',
  'amount_input': 'Введите количество',
  'piece': 'шт',
  'cencal': 'Отмена',
  'confirmation': 'Подтверждение',
  'delete': 'Удалить',
  'yes': 'Да',
  'error': 'Ошибка',
  'loading': 'Загрузка',
  'add': 'Добавить',
  'title': 'Название',
  'input_title': 'Введите название',
  'size': 'Размер',
  'update': 'Обновить',
};
