const Map<String, String> uzUz = {
  'appName': 'TimeFlow',
  'language':"Til",
  'settings':'Sozlamalar',
  'theme_mode': "Tungi rejim",
  'user_info':'User Info',
  'about_app':'Ilova Haqida',
  'user_settings':'Foydalanuvchi sozlamasi',
  'log_out':'Tizimdan chiqish',
  'payment_report':'To\'lov tarixi bo\'sh',



  //SIGN IN va LOGIN
  'sign_up': 'Sign Up',
  'name': 'Ism',
  'name_input': 'Ism kiriting',
  'email':'Email',
  'email_input':'Email kiriting',
  'ac_pass': 'Parol',
  'ac_pass_input':'Parol kiriting',
  'signup_button':'Ro\'yxatdan o\'tish',
  'login_button': 'Tizimga kirish',
  'have_account?':'Sizda account mavjudmi ?',
  'invalid_email': 'Email no\'tog\'ri',
  'don\'t_have_account?': 'Sizda account mavjum emasmi ?',
  'login':'Login',
  'error_signup':'Ro\'yxatdan o\'tishda xatolik yuz berdi',
  'error_login':'Login yoki parol xato',
  //report 
  'reports': 'Hisobotlar',
  'report_empty':'Hisobotlar yo\'q',
  'report_nofount':'Hisobot topilmadi',
  'report_drink':'Ichimlik Hisoboti',
  'report_food':'Ovqat Hisoboti',
  'report_bar':'Bar Hisoboti',
  //Table 
  'table_title': 'Stollar',
  'table_page_empty':'Hozircha stol mavjud emas',
  'add_table':'Yangi stol qo\'shish',
  'table_name':'Stol nomi',
  'input_table_name':'Nomni kiriting',
  'table_number':'Stol raqami',
  'input_table_number': 'Stol raqamini kiriting',
  'table_price':'Narxi (soatiga)',
  'input_table_price':'Narx kiriting',
  'busy_table':'nomli tableni band qilish',
  'booking':'Band qilish',
  'table_delete':'nomli table o\'chirilsinmi ?',
  'table_finish':'Stolni tugatish',
  'table_finish_want':'Bu Stolni tugatmoqchimisiz ?',
  //Bar
  'bar_title':'Bar',
  'food_empty':'Ovqat mavjud emas',
  'food_delete':'Taomni o\'chirish',
  'food_delete_want':'nomli taom o\'chirilsinmi?',
  'food_add':'Yangi taom qo\'shish',
  'drink_empty':'Ichimliklar mavjud emas',
  'edit_food':'Taomni tahrirlash',
  'edit_drink':'Ichimlikni tahrirlash',
  'delete_drink':'Ichimlikni o\'chirish',
  'drink_delete_want':'nomli ichimlik o\'chirilsinmi ?',
  'drink_add':'Ichimlik qo\'shish',
  'category':'Kategoriya',
  'input_category':'Kategoriya kiriting',
  //Payment
  'payment_title':'To\'lov',
  'payment_page':'To\'lov sahifasi',
  'paymenting_sum':'To\'lov miqdori',
  'payment_sum' : 'Tolangan miqdor:',
  'payment_type' : 'Tolov turi',
  'cash': 'naqt',
  'click':'click',
  'description':'Izoh',
  'payment_time':'Tolov vaqti:',
  'input_sum':'Miqdor kiriting',
  //Session
  'start_time':'Boshlangan vaqt:',
  'end_time':'Tugatilgan vaqt:',
  'duration':'O\'tgan vaqt:',
  'table_sum':'Stol narxi',
  'bar_sum':'Bar narxi:',
  'total_sum':'Jami narx:',
  'completion' :'Yakunlash',
  'session_null':'Session topilmadi',
  'session_incomplete':'Session ma\'lumotlari to\'liq emas',
  //Order
  'order_title':'Buyurtmalar',
  'order_time' :"Buyurtma vaqti:",
  'order_price':"Buyurtma narxi:",
  'order_add':'Buyurtma Qo\'shish',
  'order_food_empty':'Ovqat buyurtmasi yo\'q',
  'order_drink_empty':'Ichimlik buyurtmasi yo\'q',
  'food':"Ovqatlar",
  'drink':'Ichimliklar',
  //HOME
  'home': 'Home',
  'bar':'Bar',



  //Public
  'save':'Saqlash',
  'price':'Narxi',
  'status':'Holati',
  'amount':'Miqdori',
  'amount_input':'Sonini kiriting',
  'piece': 'dona',
  'cencal':'bekor qilish',
  'confirmation':'tasdiqlash',
  'delete':'O\'chirish',
  'yes':'Ha',
  'error':'Xatolik',
  'loading':'kutish',
  'add':'Qo\'shish',
  'title':'Nomi',
  'input_title':'Nomni kiriting',
  'size':'Hajmi',
  'update':'Yangilash',
  


  
};
